### ISSUE TITLE
Does it encrypt the full HDD ? and what is the dotnet version required ?

### ISSUE THREAD

**Issue by Abraham313** [povlteksttv/Povlsomware#1]
Hi ,glad to see this educational project .
Does it encrypt the full HDD ? and what is the dotnet version required  for run this exe?
would you  mind please,will you add *.txt file creation with message option please ?
Thanks

**Comment by povlteksttv** [comment]
Hi, glad you like it. 

No it does not do full HDD encryption. It only encrypts files. 

The dotnet version is v4.7.2. 

What do you mean with .txt file creation? Do you mean like a ransom-note?
